# Default values for helloworld-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: sameersbn/gitlab
  tag: 11.8.0
  pullPolicy: IfNotPresent

redisimage:
  registry: docker.io
  repository: sameersbn/redis
  tag: 4.0.9-2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Configure the timezone for the gitlab application. This configuration does not effect cron jobs. 
timezone: "Europe/Brussels"

# Gitlab Specifc Values
gitlab:
  # Leave blank if you want to generate a password on the fly
  root_password: 
  root_email: "admin@example.com"
  host: "example.com"
  port: "443"
  ssh_host: "ssh.example.com"
  ssh_port: "22"
  https: "true"
  self_signed: "true"
  notify_on_broken_builds: "true"
  notify_pusher: "false"
  pipeline_schedule_worker_cron: "*/5 * * * *"
  sidekiq_memory_killer_max_rss: 500000
  backup:
    schedule: "daily"
    time: "04:30"
  secrets:
    # Leave the following fields blank if you want to generate then on the fly
    db_key_base:
    key_base:
    otp_key_base:
  monitoring:
    ip_whitelist: "10.0.0.0/8"

database:
  adapter: "postgresql"
  host: "postgresql-gitlab-postgresql"
  port: "5432"
  user: "gitlab"
  # leave blank to generate one on the fly
  password: 
  name: "gitlab_production"

## Configure the ingress object to hook into existing infastructure
### ref : http://kubernetes.io/docs/user-guide/ingress/
### OPTIONALLY you can set .Values.ingress.secretName to set which secret to use
###
ingress:
  # Enable/disable exposure using ingress.
  enabled: false
  # TLS secret name.
  # tls: kong-admin.example.com-tls
  # Array of ingress hosts.
  hosts: [gitlab.example.com]
  # Map of ingress annotations.
  annotations: {}
    # kubernetes.io/ingress.class: "nginx"
    # # secretName: my-tls-cert
  # Ingress path.
  path: /


redis:
  host: "redis-gitlab-master"
  port: "6379"

gitlabmail:
  name: "gitlab-dev@example.com"
  display_name: "GitLab DEV Notification Account "
  reply_to: "gitlab-dev@example.com"

smtp:
  enabled: false
  domain: "example.com"
  host: "smtp.example.com"
  port: "587"
  user: "gitlab-dev"
  starttls: true
  authentication: "login" 

ldap: 
  enabled: false
  # The following are required parameters when moving to AD integration
  #label:   
  #host:
  #bind_dn:
  #base:
  #user_filter:

service:
  type: ClusterIP
  http:
    port: 80
    # nodePort:
  ssh: 
    port: 22
    # nodePort:
  # annotations: {}
  # loadBalancerIP: 

serviceAccount:
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  create: false
  name: default 

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "7Gi"
    cpu: "3.5"
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

persistence:
  enabled: true
  #existingClaim: 
  # storafeClass: 
  accessModes: 
    - ReadWriteOnce
  size: 10Gi


redis:
  persistence:
    enabled: true
    #existingClaim: 
    # storafeClass: 
    accessModes: 
      - ReadWriteOnce
    size: 10Gi
  service:
    type: ClusterIP
    port: 6379
    # In case of a NodePort (or LoadBalancer) value the NodePort can be explicitly given. 
    # nodePort 
    # annotations: {}
    # loadBalancerIP:

nodeSelector: {}

tolerations: []

affinity: {}
