apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab-chart.fullname" . }}-sec
  labels:
    app: {{ template "gitlab-chart.name" . }}
    chart: {{ template "gitlab-chart.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- if .Values.gitlab.root_password }}
  GITLAB_ROOT_PASSWORD: {{ .Values.gitlab.root_password | b64enc | quote }}
  {{- else }}
  GITLAB_ROOT_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.pass }}
  DB_PASS: {{ .Values.database.pass | b64enc | quote }}
  {{- else }}
  DB_PASS: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gitlab.secrets.db_key_base }}
  GITLAB_SECRETS_DB_KEY_BASE: {{ .Values.gitlab.secrets.db_key_base | b64enc | quote }}
  {{- else }}
  GITLAB_SECRETS_DB_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gitlab.secrets.key_base }}
  GITLAB_SECRETS_SECRET_KEY_BASE: {{ .Values.gitlab.secrets.key_base | b64enc | quote }}
  {{- else }}
  GITLAB_SECRETS_SECRET_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gitlab.secrets.otp_key_base }}
  GITLAB_SECRETS_OTP_KEY_BASE: {{ .Values.gitlab.secrets.otp_key_base | b64enc | quote }}
  {{- else }}
  GITLAB_SECRETS_OTP_KEY_BASE: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  LDAP_PASS: {{ required "A LDAP_PASS is needed" .Values.ldap.pass | b64enc | quote }}
  {{- end }}
