apiVersion: v1
kind: Service
metadata:
  name: {{ template "gitlab-chart.name" . }}-svc
  labels:
    app: {{ template "gitlab-chart.name" . }}
    chart: {{ template "gitlab-chart.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "LoadBalancer" -}} {{ if .Values.service.loadBalancerIP -}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{ end -}}
  {{- end -}}
  ports:
  - name: http
    port: {{ .Values.service.http.port }}
    targetPort: http
    {{- if .Values.service.http.nodePort }}
    nodePort: {{ .Values.service.http.nodePort }}
    {{- end }}
  - name: ssh
    port: {{ .Values.service.ssh.port }} 
    targetPort: ssh
    {{- if .Values.service.ssh.nodePort }}
    nodePort: {{ .Values.service.ssh.nodePort }}
    {{- end }}
  selector:
    app: {{ template "gitlab-chart.fullname" . }}
    role: gitlab-primary
